#ifndef TEST_PATHS_ABSOLUTE_H
#define TEST_PATHS_ABSOLUTE_H

#include <string>
#include <vector>

// cppclean-disable-next-line
#include "../../../src/detect.hpp"

struct AbsoluteTestCase {
    std::string path;
    bool        expected;
};

const std::vector<AbsoluteTestCase> common_cases = {
    {"",               false},
    {".",              false},
    {"..",             false},
    {"a",              false},
    {"/",              true },
    {"/.",             true },
    {"/..",            true },
    {"/a",             true },
    {"./",             false},
    {"./.",            false},
    {"./..",           false},
    {"./a",            false},
    {"../",            false},
    {"../.",           false},
    {"../..",          false},
    {"../a",           false},
    {"a/",             false},
    {"a/.",            false},
    {"a/..",           false},
    {"a/b",            false},
    {"//",             true },
    {"//.",            true },
    {"//..",           true },
    {"//a",            true },
    {"/./",            true },
    {"/./.",           true },
    {"/./..",          true },
    {"/./a",           true },
    {"/../",           true },
    {"/../.",          true },
    {"/../..",         true },
    {"/../a",          true },
    {"/a/",            true },
    {"/a/.",           true },
    {"/a/..",          true },
    {"/a/b",           true },
    {".//",            false},
    {".//.",           false},
    {".//..",          false},
    {".//a",           false},
    {"././",           false},
    {"././.",          false},
    {"././..",         false},
    {"././a",          false},
    {"./../",          false},
    {"./../.",         false},
    {"./../..",        false},
    {"./../a",         false},
    {"./a/",           false},
    {"./a/.",          false},
    {"./a/..",         false},
    {"./a/b",          false},
    {"..//",           false},
    {"..//.",          false},
    {"..//..",         false},
    {"..//a",          false},
    {".././",          false},
    {".././.",         false},
    {".././..",        false},
    {".././a",         false},
    {"../../",         false},
    {"../../.",        false},
    {"../../..",       false},
    {"../../a",        false},
    {"../a/",          false},
    {"../a/.",         false},
    {"../a/..",        false},
    {"../a/b",         false},
    {"a//",            false},
    {"a//.",           false},
    {"a//..",          false},
    {"a//b",           false},
    {"a/./",           false},
    {"a/./.",          false},
    {"a/./..",         false},
    {"a/./b",          false},
    {"a/../",          false},
    {"a/../.",         false},
    {"a/../..",        false},
    {"a/../b",         false},
    {"a/b/",           false},
    {"a/b/.",          false},
    {"a/b/..",         false},
    {"a/b/c",          false},
    {"///",            true },
    {"///.",           true },
    {"///..",          true },
    {"///a",           true },
    {"//./",           true },
    {"//./.",          true },
    {"//./..",         true },
    {"//./a",          true },
    {"//../",          true },
    {"//../.",         true },
    {"//../..",        true },
    {"//../a",         true },
    {"//a/",           true },
    {"//a/.",          true },
    {"//a/..",         true },
    {"//a/b",          true },
    {"/.//",           true },
    {"/.//.",          true },
    {"/.//..",         true },
    {"/.//a",          true },
    {"/././",          true },
    {"/././.",         true },
    {"/././..",        true },
    {"/././a",         true },
    {"/./../",         true },
    {"/./../.",        true },
    {"/./../..",       true },
    {"/./../a",        true },
    {"/./a/",          true },
    {"/./a/.",         true },
    {"/./a/..",        true },
    {"/./a/b",         true },
    {"/..//",          true },
    {"/..//.",         true },
    {"/..//..",        true },
    {"/..//a",         true },
    {"/.././",         true },
    {"/.././.",        true },
    {"/.././..",       true },
    {"/.././a",        true },
    {"/../../",        true },
    {"/../../.",       true },
    {"/../../..",      true },
    {"/../../a",       true },
    {"/../a/",         true },
    {"/../a/.",        true },
    {"/../a/..",       true },
    {"/../a/b",        true },
    {"/a//",           true },
    {"/a//.",          true },
    {"/a//..",         true },
    {"/a//b",          true },
    {"/a/./",          true },
    {"/a/./.",         true },
    {"/a/./..",        true },
    {"/a/./b",         true },
    {"/a/../",         true },
    {"/a/../.",        true },
    {"/a/../..",       true },
    {"/a/../b",        true },
    {"/a/b/",          true },
    {"/a/b/.",         true },
    {"/a/b/..",        true },
    {"/a/b/c",         true },
    {".///",           false},
    {".///.",          false},
    {".///..",         false},
    {".///a",          false},
    {".//./",          false},
    {".//./.",         false},
    {".//./..",        false},
    {".//./a",         false},
    {".//../",         false},
    {".//../.",        false},
    {".//../..",       false},
    {".//../a",        false},
    {".//a/",          false},
    {".//a/.",         false},
    {".//a/..",        false},
    {".//a/b",         false},
    {"././/",          false},
    {"././/.",         false},
    {"././/..",        false},
    {"././/a",         false},
    {"./././",         false},
    {"./././.",        false},
    {"./././..",       false},
    {"./././a",        false},
    {"././../",        false},
    {"././../.",       false},
    {"././../..",      false},
    {"././../a",       false},
    {"././a/",         false},
    {"././a/.",        false},
    {"././a/..",       false},
    {"././a/b",        false},
    {"./..//",         false},
    {"./..//.",        false},
    {"./..//..",       false},
    {"./..//a",        false},
    {"./.././",        false},
    {"./.././.",       false},
    {"./.././..",      false},
    {"./.././a",       false},
    {"./../../",       false},
    {"./../../.",      false},
    {"./../../..",     false},
    {"./../../a",      false},
    {"./../a/",        false},
    {"./../a/.",       false},
    {"./../a/..",      false},
    {"./../a/b",       false},
    {"./a//",          false},
    {"./a//.",         false},
    {"./a//..",        false},
    {"./a//b",         false},
    {"./a/./",         false},
    {"./a/./.",        false},
    {"./a/./..",       false},
    {"./a/./b",        false},
    {"./a/../",        false},
    {"./a/../.",       false},
    {"./a/../..",      false},
    {"./a/../b",       false},
    {"./a/b/",         false},
    {"./a/b/.",        false},
    {"./a/b/..",       false},
    {"./a/b/c",        false},
    {"..///",          false},
    {"..///.",         false},
    {"..///..",        false},
    {"..///a",         false},
    {"..//./",         false},
    {"..//./.",        false},
    {"..//./..",       false},
    {"..//./a",        false},
    {"..//../",        false},
    {"..//../.",       false},
    {"..//../..",      false},
    {"..//../a",       false},
    {"..//a/",         false},
    {"..//a/.",        false},
    {"..//a/..",       false},
    {"..//a/b",        false},
    {".././/",         false},
    {".././/.",        false},
    {".././/..",       false},
    {".././/a",        false},
    {"../././",        false},
    {"../././.",       false},
    {"../././..",      false},
    {"../././a",       false},
    {".././../",       false},
    {".././../.",      false},
    {".././../..",     false},
    {".././../a",      false},
    {".././a/",        false},
    {".././a/.",       false},
    {".././a/..",      false},
    {".././a/b",       false},
    {"../..//",        false},
    {"../..//.",       false},
    {"../..//..",      false},
    {"../..//a",       false},
    {"../.././",       false},
    {"../.././.",      false},
    {"../.././..",     false},
    {"../.././a",      false},
    {"../../../",      false},
    {"../../../.",     false},
    {"../../../..",    false},
    {"../../../a",     false},
    {"../../a/",       false},
    {"../../a/.",      false},
    {"../../a/..",     false},
    {"../../a/b",      false},
    {"../a//",         false},
    {"../a//.",        false},
    {"../a//..",       false},
    {"../a//b",        false},
    {"../a/./",        false},
    {"../a/./.",       false},
    {"../a/./..",      false},
    {"../a/./b",       false},
    {"../a/../",       false},
    {"../a/../.",      false},
    {"../a/../..",     false},
    {"../a/../b",      false},
    {"../a/b/",        false},
    {"../a/b/.",       false},
    {"../a/b/..",      false},
    {"../a/b/c",       false},
    {"a///",           false},
    {"a///.",          false},
    {"a///..",         false},
    {"a///b",          false},
    {"a//./",          false},
    {"a//./.",         false},
    {"a//./..",        false},
    {"a//./b",         false},
    {"a//../",         false},
    {"a//../.",        false},
    {"a//../..",       false},
    {"a//../b",        false},
    {"a//b/",          false},
    {"a//b/.",         false},
    {"a//b/..",        false},
    {"a//b/c",         false},
    {"a/.//",          false},
    {"a/.//.",         false},
    {"a/.//..",        false},
    {"a/.//b",         false},
    {"a/././",         false},
    {"a/././.",        false},
    {"a/././..",       false},
    {"a/././b",        false},
    {"a/./../",        false},
    {"a/./../.",       false},
    {"a/./../..",      false},
    {"a/./../b",       false},
    {"a/./b/",         false},
    {"a/./b/.",        false},
    {"a/./b/..",       false},
    {"a/./b/c",        false},
    {"a/..//",         false},
    {"a/..//.",        false},
    {"a/..//..",       false},
    {"a/..//b",        false},
    {"a/.././",        false},
    {"a/.././.",       false},
    {"a/.././..",      false},
    {"a/.././b",       false},
    {"a/../../",       false},
    {"a/../../.",      false},
    {"a/../../..",     false},
    {"a/../../b",      false},
    {"a/../b/",        false},
    {"a/../b/.",       false},
    {"a/../b/..",      false},
    {"a/../b/c",       false},
    {"a/b//",          false},
    {"a/b//.",         false},
    {"a/b//..",        false},
    {"a/b//c",         false},
    {"a/b/./",         false},
    {"a/b/./.",        false},
    {"a/b/./..",       false},
    {"a/b/./c",        false},
    {"a/b/../",        false},
    {"a/b/../.",       false},
    {"a/b/../..",      false},
    {"a/b/../c",       false},
    {"a/b/c/",         false},
    {"a/b/c/.",        false},
    {"a/b/c/..",       false},
    {"a/b/c/d",        false},
    {"////",           true },
    {"////.",          true },
    {"////..",         true },
    {"////a",          true },
    {"///./",          true },
    {"///./.",         true },
    {"///./..",        true },
    {"///./a",         true },
    {"///../",         true },
    {"///../.",        true },
    {"///../..",       true },
    {"///../a",        true },
    {"///a/",          true },
    {"///a/.",         true },
    {"///a/..",        true },
    {"///a/b",         true },
    {"//.//",          true },
    {"//.//.",         true },
    {"//.//..",        true },
    {"//.//a",         true },
    {"//././",         true },
    {"//././.",        true },
    {"//././..",       true },
    {"//././a",        true },
    {"//./../",        true },
    {"//./../.",       true },
    {"//./../..",      true },
    {"//./../a",       true },
    {"//./a/",         true },
    {"//./a/.",        true },
    {"//./a/..",       true },
    {"//./a/b",        true },
    {"//..//",         true },
    {"//..//.",        true },
    {"//..//..",       true },
    {"//..//a",        true },
    {"//.././",        true },
    {"//.././.",       true },
    {"//.././..",      true },
    {"//.././a",       true },
    {"//../../",       true },
    {"//../../.",      true },
    {"//../../..",     true },
    {"//../../a",      true },
    {"//../a/",        true },
    {"//../a/.",       true },
    {"//../a/..",      true },
    {"//../a/b",       true },
    {"//a//",          true },
    {"//a//.",         true },
    {"//a//..",        true },
    {"//a//b",         true },
    {"//a/./",         true },
    {"//a/./.",        true },
    {"//a/./..",       true },
    {"//a/./b",        true },
    {"//a/../",        true },
    {"//a/../.",       true },
    {"//a/../..",      true },
    {"//a/../b",       true },
    {"//a/b/",         true },
    {"//a/b/.",        true },
    {"//a/b/..",       true },
    {"//a/b/c",        true },
    {"/.///",          true },
    {"/.///.",         true },
    {"/.///..",        true },
    {"/.///a",         true },
    {"/.//./",         true },
    {"/.//./.",        true },
    {"/.//./..",       true },
    {"/.//./a",        true },
    {"/.//../",        true },
    {"/.//../.",       true },
    {"/.//../..",      true },
    {"/.//../a",       true },
    {"/.//a/",         true },
    {"/.//a/.",        true },
    {"/.//a/..",       true },
    {"/.//a/b",        true },
    {"/././/",         true },
    {"/././/.",        true },
    {"/././/..",       true },
    {"/././/a",        true },
    {"/./././",        true },
    {"/./././.",       true },
    {"/./././..",      true },
    {"/./././a",       true },
    {"/././../",       true },
    {"/././../.",      true },
    {"/././../..",     true },
    {"/././../a",      true },
    {"/././a/",        true },
    {"/././a/.",       true },
    {"/././a/..",      true },
    {"/././a/b",       true },
    {"/./..//",        true },
    {"/./..//.",       true },
    {"/./..//..",      true },
    {"/./..//a",       true },
    {"/./.././",       true },
    {"/./.././.",      true },
    {"/./.././..",     true },
    {"/./.././a",      true },
    {"/./../../",      true },
    {"/./../../.",     true },
    {"/./../../..",    true },
    {"/./../../a",     true },
    {"/./../a/",       true },
    {"/./../a/.",      true },
    {"/./../a/..",     true },
    {"/./../a/b",      true },
    {"/./a//",         true },
    {"/./a//.",        true },
    {"/./a//..",       true },
    {"/./a//b",        true },
    {"/./a/./",        true },
    {"/./a/./.",       true },
    {"/./a/./..",      true },
    {"/./a/./b",       true },
    {"/./a/../",       true },
    {"/./a/../.",      true },
    {"/./a/../..",     true },
    {"/./a/../b",      true },
    {"/./a/b/",        true },
    {"/./a/b/.",       true },
    {"/./a/b/..",      true },
    {"/./a/b/c",       true },
    {"/..///",         true },
    {"/..///.",        true },
    {"/..///..",       true },
    {"/..///a",        true },
    {"/..//./",        true },
    {"/..//./.",       true },
    {"/..//./..",      true },
    {"/..//./a",       true },
    {"/..//../",       true },
    {"/..//../.",      true },
    {"/..//../..",     true },
    {"/..//../a",      true },
    {"/..//a/",        true },
    {"/..//a/.",       true },
    {"/..//a/..",      true },
    {"/..//a/b",       true },
    {"/.././/",        true },
    {"/.././/.",       true },
    {"/.././/..",      true },
    {"/.././/a",       true },
    {"/../././",       true },
    {"/../././.",      true },
    {"/../././..",     true },
    {"/../././a",      true },
    {"/.././../",      true },
    {"/.././../.",     true },
    {"/.././../..",    true },
    {"/.././../a",     true },
    {"/.././a/",       true },
    {"/.././a/.",      true },
    {"/.././a/..",     true },
    {"/.././a/b",      true },
    {"/../..//",       true },
    {"/../..//.",      true },
    {"/../..//..",     true },
    {"/../..//a",      true },
    {"/../.././",      true },
    {"/../.././.",     true },
    {"/../.././..",    true },
    {"/../.././a",     true },
    {"/../../../",     true },
    {"/../../../.",    true },
    {"/../../../..",   true },
    {"/../../../a",    true },
    {"/../../a/",      true },
    {"/../../a/.",     true },
    {"/../../a/..",    true },
    {"/../../a/b",     true },
    {"/../a//",        true },
    {"/../a//.",       true },
    {"/../a//..",      true },
    {"/../a//b",       true },
    {"/../a/./",       true },
    {"/../a/./.",      true },
    {"/../a/./..",     true },
    {"/../a/./b",      true },
    {"/../a/../",      true },
    {"/../a/../.",     true },
    {"/../a/../..",    true },
    {"/../a/../b",     true },
    {"/../a/b/",       true },
    {"/../a/b/.",      true },
    {"/../a/b/..",     true },
    {"/../a/b/c",      true },
    {"/a///",          true },
    {"/a///.",         true },
    {"/a///..",        true },
    {"/a///b",         true },
    {"/a//./",         true },
    {"/a//./.",        true },
    {"/a//./..",       true },
    {"/a//./b",        true },
    {"/a//../",        true },
    {"/a//../.",       true },
    {"/a//../..",      true },
    {"/a//../b",       true },
    {"/a//b/",         true },
    {"/a//b/.",        true },
    {"/a//b/..",       true },
    {"/a//b/c",        true },
    {"/a/.//",         true },
    {"/a/.//.",        true },
    {"/a/.//..",       true },
    {"/a/.//b",        true },
    {"/a/././",        true },
    {"/a/././.",       true },
    {"/a/././..",      true },
    {"/a/././b",       true },
    {"/a/./../",       true },
    {"/a/./../.",      true },
    {"/a/./../..",     true },
    {"/a/./../b",      true },
    {"/a/./b/",        true },
    {"/a/./b/.",       true },
    {"/a/./b/..",      true },
    {"/a/./b/c",       true },
    {"/a/..//",        true },
    {"/a/..//.",       true },
    {"/a/..//..",      true },
    {"/a/..//b",       true },
    {"/a/.././",       true },
    {"/a/.././.",      true },
    {"/a/.././..",     true },
    {"/a/.././b",      true },
    {"/a/../../",      true },
    {"/a/../../.",     true },
    {"/a/../../..",    true },
    {"/a/../../b",     true },
    {"/a/../b/",       true },
    {"/a/../b/.",      true },
    {"/a/../b/..",     true },
    {"/a/../b/c",      true },
    {"/a/b//",         true },
    {"/a/b//.",        true },
    {"/a/b//..",       true },
    {"/a/b//c",        true },
    {"/a/b/./",        true },
    {"/a/b/./.",       true },
    {"/a/b/./..",      true },
    {"/a/b/./c",       true },
    {"/a/b/../",       true },
    {"/a/b/../.",      true },
    {"/a/b/../..",     true },
    {"/a/b/../c",      true },
    {"/a/b/c/",        true },
    {"/a/b/c/.",       true },
    {"/a/b/c/..",      true },
    {"/a/b/c/d",       true },
    {".////",          false},
    {".////.",         false},
    {".////..",        false},
    {".////a",         false},
    {".///./",         false},
    {".///./.",        false},
    {".///./..",       false},
    {".///./a",        false},
    {".///../",        false},
    {".///../.",       false},
    {".///../..",      false},
    {".///../a",       false},
    {".///a/",         false},
    {".///a/.",        false},
    {".///a/..",       false},
    {".///a/b",        false},
    {".//.//",         false},
    {".//.//.",        false},
    {".//.//..",       false},
    {".//.//a",        false},
    {".//././",        false},
    {".//././.",       false},
    {".//././..",      false},
    {".//././a",       false},
    {".//./../",       false},
    {".//./../.",      false},
    {".//./../..",     false},
    {".//./../a",      false},
    {".//./a/",        false},
    {".//./a/.",       false},
    {".//./a/..",      false},
    {".//./a/b",       false},
    {".//..//",        false},
    {".//..//.",       false},
    {".//..//..",      false},
    {".//..//a",       false},
    {".//.././",       false},
    {".//.././.",      false},
    {".//.././..",     false},
    {".//.././a",      false},
    {".//../../",      false},
    {".//../../.",     false},
    {".//../../..",    false},
    {".//../../a",     false},
    {".//../a/",       false},
    {".//../a/.",      false},
    {".//../a/..",     false},
    {".//../a/b",      false},
    {".//a//",         false},
    {".//a//.",        false},
    {".//a//..",       false},
    {".//a//b",        false},
    {".//a/./",        false},
    {".//a/./.",       false},
    {".//a/./..",      false},
    {".//a/./b",       false},
    {".//a/../",       false},
    {".//a/../.",      false},
    {".//a/../..",     false},
    {".//a/../b",      false},
    {".//a/b/",        false},
    {".//a/b/.",       false},
    {".//a/b/..",      false},
    {".//a/b/c",       false},
    {"././//",         false},
    {"././//.",        false},
    {"././//..",       false},
    {"././//a",        false},
    {"././/./",        false},
    {"././/./.",       false},
    {"././/./..",      false},
    {"././/./a",       false},
    {"././/../",       false},
    {"././/../.",      false},
    {"././/../..",     false},
    {"././/../a",      false},
    {"././/a/",        false},
    {"././/a/.",       false},
    {"././/a/..",      false},
    {"././/a/b",       false},
    {"./././/",        false},
    {"./././/.",       false},
    {"./././/..",      false},
    {"./././/a",       false},
    {"././././",       false},
    {"././././.",      false},
    {"././././..",     false},
    {"././././a",      false},
    {"./././../",      false},
    {"./././../.",     false},
    {"./././../..",    false},
    {"./././../a",     false},
    {"./././a/",       false},
    {"./././a/.",      false},
    {"./././a/..",     false},
    {"./././a/b",      false},
    {"././..//",       false},
    {"././..//.",      false},
    {"././..//..",     false},
    {"././..//a",      false},
    {"././.././",      false},
    {"././.././.",     false},
    {"././.././..",    false},
    {"././.././a",     false},
    {"././../../",     false},
    {"././../../.",    false},
    {"././../../..",   false},
    {"././../../a",    false},
    {"././../a/",      false},
    {"././../a/.",     false},
    {"././../a/..",    false},
    {"././../a/b",     false},
    {"././a//",        false},
    {"././a//.",       false},
    {"././a//..",      false},
    {"././a//b",       false},
    {"././a/./",       false},
    {"././a/./.",      false},
    {"././a/./..",     false},
    {"././a/./b",      false},
    {"././a/../",      false},
    {"././a/../.",     false},
    {"././a/../..",    false},
    {"././a/../b",     false},
    {"././a/b/",       false},
    {"././a/b/.",      false},
    {"././a/b/..",     false},
    {"././a/b/c",      false},
    {"./..///",        false},
    {"./..///.",       false},
    {"./..///..",      false},
    {"./..///a",       false},
    {"./..//./",       false},
    {"./..//./.",      false},
    {"./..//./..",     false},
    {"./..//./a",      false},
    {"./..//../",      false},
    {"./..//../.",     false},
    {"./..//../..",    false},
    {"./..//../a",     false},
    {"./..//a/",       false},
    {"./..//a/.",      false},
    {"./..//a/..",     false},
    {"./..//a/b",      false},
    {"./.././/",       false},
    {"./.././/.",      false},
    {"./.././/..",     false},
    {"./.././/a",      false},
    {"./../././",      false},
    {"./../././.",     false},
    {"./../././..",    false},
    {"./../././a",     false},
    {"./.././../",     false},
    {"./.././../.",    false},
    {"./.././../..",   false},
    {"./.././../a",    false},
    {"./.././a/",      false},
    {"./.././a/.",     false},
    {"./.././a/..",    false},
    {"./.././a/b",     false},
    {"./../..//",      false},
    {"./../..//.",     false},
    {"./../..//..",    false},
    {"./../..//a",     false},
    {"./../.././",     false},
    {"./../.././.",    false},
    {"./../.././..",   false},
    {"./../.././a",    false},
    {"./../../../",    false},
    {"./../../../.",   false},
    {"./../../../..",  false},
    {"./../../../a",   false},
    {"./../../a/",     false},
    {"./../../a/.",    false},
    {"./../../a/..",   false},
    {"./../../a/b",    false},
    {"./../a//",       false},
    {"./../a//.",      false},
    {"./../a//..",     false},
    {"./../a//b",      false},
    {"./../a/./",      false},
    {"./../a/./.",     false},
    {"./../a/./..",    false},
    {"./../a/./b",     false},
    {"./../a/../",     false},
    {"./../a/../.",    false},
    {"./../a/../..",   false},
    {"./../a/../b",    false},
    {"./../a/b/",      false},
    {"./../a/b/.",     false},
    {"./../a/b/..",    false},
    {"./../a/b/c",     false},
    {"./a///",         false},
    {"./a///.",        false},
    {"./a///..",       false},
    {"./a///b",        false},
    {"./a//./",        false},
    {"./a//./.",       false},
    {"./a//./..",      false},
    {"./a//./b",       false},
    {"./a//../",       false},
    {"./a//../.",      false},
    {"./a//../..",     false},
    {"./a//../b",      false},
    {"./a//b/",        false},
    {"./a//b/.",       false},
    {"./a//b/..",      false},
    {"./a//b/c",       false},
    {"./a/.//",        false},
    {"./a/.//.",       false},
    {"./a/.//..",      false},
    {"./a/.//b",       false},
    {"./a/././",       false},
    {"./a/././.",      false},
    {"./a/././..",     false},
    {"./a/././b",      false},
    {"./a/./../",      false},
    {"./a/./../.",     false},
    {"./a/./../..",    false},
    {"./a/./../b",     false},
    {"./a/./b/",       false},
    {"./a/./b/.",      false},
    {"./a/./b/..",     false},
    {"./a/./b/c",      false},
    {"./a/..//",       false},
    {"./a/..//.",      false},
    {"./a/..//..",     false},
    {"./a/..//b",      false},
    {"./a/.././",      false},
    {"./a/.././.",     false},
    {"./a/.././..",    false},
    {"./a/.././b",     false},
    {"./a/../../",     false},
    {"./a/../../.",    false},
    {"./a/../../..",   false},
    {"./a/../../b",    false},
    {"./a/../b/",      false},
    {"./a/../b/.",     false},
    {"./a/../b/..",    false},
    {"./a/../b/c",     false},
    {"./a/b//",        false},
    {"./a/b//.",       false},
    {"./a/b//..",      false},
    {"./a/b//c",       false},
    {"./a/b/./",       false},
    {"./a/b/./.",      false},
    {"./a/b/./..",     false},
    {"./a/b/./c",      false},
    {"./a/b/../",      false},
    {"./a/b/../.",     false},
    {"./a/b/../..",    false},
    {"./a/b/../c",     false},
    {"./a/b/c/",       false},
    {"./a/b/c/.",      false},
    {"./a/b/c/..",     false},
    {"./a/b/c/d",      false},
    {"..////",         false},
    {"..////.",        false},
    {"..////..",       false},
    {"..////a",        false},
    {"..///./",        false},
    {"..///./.",       false},
    {"..///./..",      false},
    {"..///./a",       false},
    {"..///../",       false},
    {"..///../.",      false},
    {"..///../..",     false},
    {"..///../a",      false},
    {"..///a/",        false},
    {"..///a/.",       false},
    {"..///a/..",      false},
    {"..///a/b",       false},
    {"..//.//",        false},
    {"..//.//.",       false},
    {"..//.//..",      false},
    {"..//.//a",       false},
    {"..//././",       false},
    {"..//././.",      false},
    {"..//././..",     false},
    {"..//././a",      false},
    {"..//./../",      false},
    {"..//./../.",     false},
    {"..//./../..",    false},
    {"..//./../a",     false},
    {"..//./a/",       false},
    {"..//./a/.",      false},
    {"..//./a/..",     false},
    {"..//./a/b",      false},
    {"..//..//",       false},
    {"..//..//.",      false},
    {"..//..//..",     false},
    {"..//..//a",      false},
    {"..//.././",      false},
    {"..//.././.",     false},
    {"..//.././..",    false},
    {"..//.././a",     false},
    {"..//../../",     false},
    {"..//../../.",    false},
    {"..//../../..",   false},
    {"..//../../a",    false},
    {"..//../a/",      false},
    {"..//../a/.",     false},
    {"..//../a/..",    false},
    {"..//../a/b",     false},
    {"..//a//",        false},
    {"..//a//.",       false},
    {"..//a//..",      false},
    {"..//a//b",       false},
    {"..//a/./",       false},
    {"..//a/./.",      false},
    {"..//a/./..",     false},
    {"..//a/./b",      false},
    {"..//a/../",      false},
    {"..//a/../.",     false},
    {"..//a/../..",    false},
    {"..//a/../b",     false},
    {"..//a/b/",       false},
    {"..//a/b/.",      false},
    {"..//a/b/..",     false},
    {"..//a/b/c",      false},
    {".././//",        false},
    {".././//.",       false},
    {".././//..",      false},
    {".././//a",       false},
    {".././/./",       false},
    {".././/./.",      false},
    {".././/./..",     false},
    {".././/./a",      false},
    {".././/../",      false},
    {".././/../.",     false},
    {".././/../..",    false},
    {".././/../a",     false},
    {".././/a/",       false},
    {".././/a/.",      false},
    {".././/a/..",     false},
    {".././/a/b",      false},
    {"../././/",       false},
    {"../././/.",      false},
    {"../././/..",     false},
    {"../././/a",      false},
    {".././././",      false},
    {".././././.",     false},
    {".././././..",    false},
    {".././././a",     false},
    {"../././../",     false},
    {"../././../.",    false},
    {"../././../..",   false},
    {"../././../a",    false},
    {"../././a/",      false},
    {"../././a/.",     false},
    {"../././a/..",    false},
    {"../././a/b",     false},
    {".././..//",      false},
    {".././..//.",     false},
    {".././..//..",    false},
    {".././..//a",     false},
    {".././.././",     false},
    {".././.././.",    false},
    {".././.././..",   false},
    {".././.././a",    false},
    {".././../../",    false},
    {".././../../.",   false},
    {".././../../..",  false},
    {".././../../a",   false},
    {".././../a/",     false},
    {".././../a/.",    false},
    {".././../a/..",   false},
    {".././../a/b",    false},
    {".././a//",       false},
    {".././a//.",      false},
    {".././a//..",     false},
    {".././a//b",      false},
    {".././a/./",      false},
    {".././a/./.",     false},
    {".././a/./..",    false},
    {".././a/./b",     false},
    {".././a/../",     false},
    {".././a/../.",    false},
    {".././a/../..",   false},
    {".././a/../b",    false},
    {".././a/b/",      false},
    {".././a/b/.",     false},
    {".././a/b/..",    false},
    {".././a/b/c",     false},
    {"../..///",       false},
    {"../..///.",      false},
    {"../..///..",     false},
    {"../..///a",      false},
    {"../..//./",      false},
    {"../..//./.",     false},
    {"../..//./..",    false},
    {"../..//./a",     false},
    {"../..//../",     false},
    {"../..//../.",    false},
    {"../..//../..",   false},
    {"../..//../a",    false},
    {"../..//a/",      false},
    {"../..//a/.",     false},
    {"../..//a/..",    false},
    {"../..//a/b",     false},
    {"../.././/",      false},
    {"../.././/.",     false},
    {"../.././/..",    false},
    {"../.././/a",     false},
    {"../../././",     false},
    {"../../././.",    false},
    {"../../././..",   false},
    {"../../././a",    false},
    {"../.././../",    false},
    {"../.././../.",   false},
    {"../.././../..",  false},
    {"../.././../a",   false},
    {"../.././a/",     false},
    {"../.././a/.",    false},
    {"../.././a/..",   false},
    {"../.././a/b",    false},
    {"../../..//",     false},
    {"../../..//.",    false},
    {"../../..//..",   false},
    {"../../..//a",    false},
    {"../../.././",    false},
    {"../../.././.",   false},
    {"../../.././..",  false},
    {"../../.././a",   false},
    {"../../../../",   false},
    {"../../../../.",  false},
    {"../../../../..", false},
    {"../../../../a",  false},
    {"../../../a/",    false},
    {"../../../a/.",   false},
    {"../../../a/..",  false},
    {"../../../a/b",   false},
    {"../../a//",      false},
    {"../../a//.",     false},
    {"../../a//..",    false},
    {"../../a//b",     false},
    {"../../a/./",     false},
    {"../../a/./.",    false},
    {"../../a/./..",   false},
    {"../../a/./b",    false},
    {"../../a/../",    false},
    {"../../a/../.",   false},
    {"../../a/../..",  false},
    {"../../a/../b",   false},
    {"../../a/b/",     false},
    {"../../a/b/.",    false},
    {"../../a/b/..",   false},
    {"../../a/b/c",    false},
    {"../a///",        false},
    {"../a///.",       false},
    {"../a///..",      false},
    {"../a///b",       false},
    {"../a//./",       false},
    {"../a//./.",      false},
    {"../a//./..",     false},
    {"../a//./b",      false},
    {"../a//../",      false},
    {"../a//../.",     false},
    {"../a//../..",    false},
    {"../a//../b",     false},
    {"../a//b/",       false},
    {"../a//b/.",      false},
    {"../a//b/..",     false},
    {"../a//b/c",      false},
    {"../a/.//",       false},
    {"../a/.//.",      false},
    {"../a/.//..",     false},
    {"../a/.//b",      false},
    {"../a/././",      false},
    {"../a/././.",     false},
    {"../a/././..",    false},
    {"../a/././b",     false},
    {"../a/./../",     false},
    {"../a/./../.",    false},
    {"../a/./../..",   false},
    {"../a/./../b",    false},
    {"../a/./b/",      false},
    {"../a/./b/.",     false},
    {"../a/./b/..",    false},
    {"../a/./b/c",     false},
    {"../a/..//",      false},
    {"../a/..//.",     false},
    {"../a/..//..",    false},
    {"../a/..//b",     false},
    {"../a/.././",     false},
    {"../a/.././.",    false},
    {"../a/.././..",   false},
    {"../a/.././b",    false},
    {"../a/../../",    false},
    {"../a/../../.",   false},
    {"../a/../../..",  false},
    {"../a/../../b",   false},
    {"../a/../b/",     false},
    {"../a/../b/.",    false},
    {"../a/../b/..",   false},
    {"../a/../b/c",    false},
    {"../a/b//",       false},
    {"../a/b//.",      false},
    {"../a/b//..",     false},
    {"../a/b//c",      false},
    {"../a/b/./",      false},
    {"../a/b/./.",     false},
    {"../a/b/./..",    false},
    {"../a/b/./c",     false},
    {"../a/b/../",     false},
    {"../a/b/../.",    false},
    {"../a/b/../..",   false},
    {"../a/b/../c",    false},
    {"../a/b/c/",      false},
    {"../a/b/c/.",     false},
    {"../a/b/c/..",    false},
    {"../a/b/c/d",     false},
    {"a////",          false},
    {"a////.",         false},
    {"a////..",        false},
    {"a////b",         false},
    {"a///./",         false},
    {"a///./.",        false},
    {"a///./..",       false},
    {"a///./b",        false},
    {"a///../",        false},
    {"a///../.",       false},
    {"a///../..",      false},
    {"a///../b",       false},
    {"a///b/",         false},
    {"a///b/.",        false},
    {"a///b/..",       false},
    {"a///b/c",        false},
    {"a//.//",         false},
    {"a//.//.",        false},
    {"a//.//..",       false},
    {"a//.//b",        false},
    {"a//././",        false},
    {"a//././.",       false},
    {"a//././..",      false},
    {"a//././b",       false},
    {"a//./../",       false},
    {"a//./../.",      false},
    {"a//./../..",     false},
    {"a//./../b",      false},
    {"a//./b/",        false},
    {"a//./b/.",       false},
    {"a//./b/..",      false},
    {"a//./b/c",       false},
    {"a//..//",        false},
    {"a//..//.",       false},
    {"a//..//..",      false},
    {"a//..//b",       false},
    {"a//.././",       false},
    {"a//.././.",      false},
    {"a//.././..",     false},
    {"a//.././b",      false},
    {"a//../../",      false},
    {"a//../../.",     false},
    {"a//../../..",    false},
    {"a//../../b",     false},
    {"a//../b/",       false},
    {"a//../b/.",      false},
    {"a//../b/..",     false},
    {"a//../b/c",      false},
    {"a//b//",         false},
    {"a//b//.",        false},
    {"a//b//..",       false},
    {"a//b//c",        false},
    {"a//b/./",        false},
    {"a//b/./.",       false},
    {"a//b/./..",      false},
    {"a//b/./c",       false},
    {"a//b/../",       false},
    {"a//b/../.",      false},
    {"a//b/../..",     false},
    {"a//b/../c",      false},
    {"a//b/c/",        false},
    {"a//b/c/.",       false},
    {"a//b/c/..",      false},
    {"a//b/c/d",       false},
    {"a/.///",         false},
    {"a/.///.",        false},
    {"a/.///..",       false},
    {"a/.///b",        false},
    {"a/.//./",        false},
    {"a/.//./.",       false},
    {"a/.//./..",      false},
    {"a/.//./b",       false},
    {"a/.//../",       false},
    {"a/.//../.",      false},
    {"a/.//../..",     false},
    {"a/.//../b",      false},
    {"a/.//b/",        false},
    {"a/.//b/.",       false},
    {"a/.//b/..",      false},
    {"a/.//b/c",       false},
    {"a/././/",        false},
    {"a/././/.",       false},
    {"a/././/..",      false},
    {"a/././/b",       false},
    {"a/./././",       false},
    {"a/./././.",      false},
    {"a/./././..",     false},
    {"a/./././b",      false},
    {"a/././../",      false},
    {"a/././../.",     false},
    {"a/././../..",    false},
    {"a/././../b",     false},
    {"a/././b/",       false},
    {"a/././b/.",      false},
    {"a/././b/..",     false},
    {"a/././b/c",      false},
    {"a/./..//",       false},
    {"a/./..//.",      false},
    {"a/./..//..",     false},
    {"a/./..//b",      false},
    {"a/./.././",      false},
    {"a/./.././.",     false},
    {"a/./.././..",    false},
    {"a/./.././b",     false},
    {"a/./../../",     false},
    {"a/./../../.",    false},
    {"a/./../../..",   false},
    {"a/./../../b",    false},
    {"a/./../b/",      false},
    {"a/./../b/.",     false},
    {"a/./../b/..",    false},
    {"a/./../b/c",     false},
    {"a/./b//",        false},
    {"a/./b//.",       false},
    {"a/./b//..",      false},
    {"a/./b//c",       false},
    {"a/./b/./",       false},
    {"a/./b/./.",      false},
    {"a/./b/./..",     false},
    {"a/./b/./c",      false},
    {"a/./b/../",      false},
    {"a/./b/../.",     false},
    {"a/./b/../..",    false},
    {"a/./b/../c",     false},
    {"a/./b/c/",       false},
    {"a/./b/c/.",      false},
    {"a/./b/c/..",     false},
    {"a/./b/c/d",      false},
    {"a/..///",        false},
    {"a/..///.",       false},
    {"a/..///..",      false},
    {"a/..///b",       false},
    {"a/..//./",       false},
    {"a/..//./.",      false},
    {"a/..//./..",     false},
    {"a/..//./b",      false},
    {"a/..//../",      false},
    {"a/..//../.",     false},
    {"a/..//../..",    false},
    {"a/..//../b",     false},
    {"a/..//b/",       false},
    {"a/..//b/.",      false},
    {"a/..//b/..",     false},
    {"a/..//b/c",      false},
    {"a/.././/",       false},
    {"a/.././/.",      false},
    {"a/.././/..",     false},
    {"a/.././/b",      false},
    {"a/../././",      false},
    {"a/../././.",     false},
    {"a/../././..",    false},
    {"a/../././b",     false},
    {"a/.././../",     false},
    {"a/.././../.",    false},
    {"a/.././../..",   false},
    {"a/.././../b",    false},
    {"a/.././b/",      false},
    {"a/.././b/.",     false},
    {"a/.././b/..",    false},
    {"a/.././b/c",     false},
    {"a/../..//",      false},
    {"a/../..//.",     false},
    {"a/../..//..",    false},
    {"a/../..//b",     false},
    {"a/../.././",     false},
    {"a/../.././.",    false},
    {"a/../.././..",   false},
    {"a/../.././b",    false},
    {"a/../../../",    false},
    {"a/../../../.",   false},
    {"a/../../../..",  false},
    {"a/../../../b",   false},
    {"a/../../b/",     false},
    {"a/../../b/.",    false},
    {"a/../../b/..",   false},
    {"a/../../b/c",    false},
    {"a/../b//",       false},
    {"a/../b//.",      false},
    {"a/../b//..",     false},
    {"a/../b//c",      false},
    {"a/../b/./",      false},
    {"a/../b/./.",     false},
    {"a/../b/./..",    false},
    {"a/../b/./c",     false},
    {"a/../b/../",     false},
    {"a/../b/../.",    false},
    {"a/../b/../..",   false},
    {"a/../b/../c",    false},
    {"a/../b/c/",      false},
    {"a/../b/c/.",     false},
    {"a/../b/c/..",    false},
    {"a/../b/c/d",     false},
    {"a/b///",         false},
    {"a/b///.",        false},
    {"a/b///..",       false},
    {"a/b///c",        false},
    {"a/b//./",        false},
    {"a/b//./.",       false},
    {"a/b//./..",      false},
    {"a/b//./c",       false},
    {"a/b//../",       false},
    {"a/b//../.",      false},
    {"a/b//../..",     false},
    {"a/b//../c",      false},
    {"a/b//c/",        false},
    {"a/b//c/.",       false},
    {"a/b//c/..",      false},
    {"a/b//c/d",       false},
    {"a/b/.//",        false},
    {"a/b/.//.",       false},
    {"a/b/.//..",      false},
    {"a/b/.//c",       false},
    {"a/b/././",       false},
    {"a/b/././.",      false},
    {"a/b/././..",     false},
    {"a/b/././c",      false},
    {"a/b/./../",      false},
    {"a/b/./../.",     false},
    {"a/b/./../..",    false},
    {"a/b/./../c",     false},
    {"a/b/./c/",       false},
    {"a/b/./c/.",      false},
    {"a/b/./c/..",     false},
    {"a/b/./c/d",      false},
    {"a/b/..//",       false},
    {"a/b/..//.",      false},
    {"a/b/..//..",     false},
    {"a/b/..//c",      false},
    {"a/b/.././",      false},
    {"a/b/.././.",     false},
    {"a/b/.././..",    false},
    {"a/b/.././c",     false},
    {"a/b/../../",     false},
    {"a/b/../../.",    false},
    {"a/b/../../..",   false},
    {"a/b/../../c",    false},
    {"a/b/../c/",      false},
    {"a/b/../c/.",     false},
    {"a/b/../c/..",    false},
    {"a/b/../c/d",     false},
    {"a/b/c//",        false},
    {"a/b/c//.",       false},
    {"a/b/c//..",      false},
    {"a/b/c//d",       false},
    {"a/b/c/./",       false},
    {"a/b/c/./.",      false},
    {"a/b/c/./..",     false},
    {"a/b/c/./d",      false},
    {"a/b/c/../",      false},
    {"a/b/c/../.",     false},
    {"a/b/c/../..",    false},
    {"a/b/c/../d",     false},
    {"a/b/c/d/",       false},
    {"a/b/c/d/.",      false},
    {"a/b/c/d/..",     false},
    {"a/b/c/d/e",      false},
};

const std::vector<AbsoluteTestCase> windows_cases = {
    {"//a/b/c", true},
    {"C:/a/b",  true},
};

const std::vector<AbsoluteTestCase> posix_cases = {
    {"//a/b/c", true },
    {"C:/a/b",  false},
};

const std::vector<AbsoluteTestCase> platform_cases = platform::os == platform::Windows ? windows_cases : posix_cases;

#endif
