name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Build docs
        run: | 
          doxygen
          ls docs/build

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          token: ${{ secrets.GITHUB_TOKEN }}
