name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-ubuntu

      - name: Run linters
        run: |
          npx cspell . --dot
          cppclean . --include-path $CPPPATH
          cppcheck **/*.*pp -q --enable=all --suppressions-list=.cppcheck
          scons --typecheck
        env:
          CPPPATH: /usr/include

      - name: Run tests
        run: |
          export DIRPATH=$PWD/$DIRNAME
          export ABSPATH=$PWD/$DIRNAME/a/b/c
          export FILEPATH=$PWD/$DIRNAME/$FILENAME
          scons
          ./dist/tests
        env:
          DIRNAME: dist
          FILENAME: tests
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
