name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run linters
        run: scons lint

      - name: Run tests
        run: scons test

      - name: Compile the tagged version with the test package
        run: >
          conan create publish/all/conanfile.py
          --version $(yq -r ".versions | keys | .[0]" publish/config.yml)
