name: Review

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install node and yarn dependencies
        uses: ./.github/actions/node

      - name: Install apt dependencies
        run: sudo apt install -y cppcheck

      - name: Run linters
        run: grunt lint

  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64

      - name: Install test dependencies
        run: sudo apt-get install libpthread-stubs0-dev lcov

      - name: Install gtest from source
        uses: ./.github/actions/gtest

      - name: Build tests
        run: |
          mkdir dist
          clang++ -std=c++11 --coverage $(find src test -name "*.cpp") -lpthread -lgtest -o dist/test

      - name: Run tests
        run: |
          export FILENAME=$PWD/dist/test
          dist/test

      - name: Generate code coverage
        run: geninfo "." --gcov-tool "/usr/local/bin/clang++" --include "${GITHUB_WORKSPACE}/src/*.cpp" -b "." -o coverage.info

      - name: Report code coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.info
