name: Review

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install node and yarn dependencies
        uses: ./.github/actions/node

      - name: Install apt dependencies
        run: sudo apt install -y cppcheck

      - name: Run linters
        run: grunt lint

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install clang 13
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64

      - name: Build gtest from source
        run: |
          git clone https://github.com/google/googletest.git -b release-1.12.0
          mkdir googletest/build
          cd googletest/build
          cmake ..
          make
          sudo make install

      - name: Build tests
        run: |
          mkdir dist
          clang++ -std=c++11 -Lgoogletest/build/lib -lgtest -o dist/test $(find . -name "*.cpp")

      - name: Run tests
        run: dist/test
        env:
          PATHNAME: dist/test
