name: Test on Ubuntu 20.04

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-ubuntu

      - name: Run tests
        run: |
          export FILEPATH=$PWD/dist/tests
          export DIRPATH=$PWD/dist
          export ABSPATH=$PWD/dist/a/b/c          
          scons tests
          ./dist/tests
        env:
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
          FILENAME: tests
          DIRNAME: dist
