name: Test on MacOS 12

on: [push, pull_request]

jobs:
  review:
    runs-on: macos-12
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-macos

      - name: Run tests
        run: |
          export DIRPATH=$PWD/$DIRNAME
          export ABSPATH=$PWD/$DIRNAME/a/b/c
          export FILEPATH=$PWD/$DIRNAME/$FILENAME
          scons
          ./dist/tests
        env:
          DIRNAME: dist
          FILENAME: tests
          CPPPATH: /opt/homebrew/include
          LIBPATH: /opt/homebrew/lib
