name: Test on Windows 2022

on: [push, pull_request]

jobs:
  review:
    runs-on: windows-2022
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run tests
        run: |
          set DIRPATH=%cd%\%DIRNAME%
          set ABSPATH=%cd%\%DIRNAME%\a\b\c
          set FILEPATH=%cd%\%DIRNAME%\%FILENAME%
          scons
          ./dist/tests
        env:
          DIRNAME: dist
          FILENAME: tests.exe
          CPPPATH: C:/Program Files (x86)/googletest-distribution/include
          LIBPATH: C:/Program Files (x86)/googletest-distribution/lib
