name: Test on Windows 2022

on: [push, pull_request]

jobs:
  review:
    runs-on: windows-2022
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-windows

      - name: Run tests
        shell: pwsh
        run: |
          set FILEPATH=%cd%/dist/tests
          set DIRPATH=%cd%/dist
          set ABSPATH=%cd%/dist/a/b/c
          
          C:\mingw64\bin\g++.exe -o test/suites/words/starts_with.o -c -std=c++17 -I/opt/homebrew/include test/suites/words/starts_with.cpp
          
          Set-Alias g++ C:\mingw64\bin\g++.exe
          g++ -o test/suites/words/starts_with.o -c -std=c++17 -I/opt/homebrew/include test/suites/words/starts_with.cpp
          
          scons
          ./dist/tests
        env:
          FILENAME: tests
          DIRNAME: dist
