name: Test on Ubuntu 20.04

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run tests
        run: |
          export DIRPATH=$PWD/$DIRNAME
          export ABSPATH=$PWD/$DIRNAME/a/b/c
          export FILEPATH=$PWD/$DIRNAME/$FILENAME
          scons
          ./dist/tests
        env:
          DIRNAME: dist
          FILENAME: tests
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
