name: Test on MacOS 12

on: [
    # push,
    pull_request,
  ]

jobs:
  review:
    runs-on: macos-12
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-macos

      - name: Run tests
        run: |
          export FILEPATH=$PWD/dist/tests
          export DIRPATH=$PWD/dist
          export ABSPATH=$PWD/dist/a/b/c
          scons
          ./dist/tests
        env:
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
          FILENAME: tests
          DIRNAME: dist
