name: Test on Windows 2022

on: [push, pull_request]

jobs:
  review:
    runs-on: windows-2022
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-windows

      - name: Run tests
        shell: pwsh
        run: |
          set FILEPATH=%cd%/dist/tests
          set DIRPATH=%cd%/dist
          set ABSPATH=%cd%/dist/a/b/c
          g++ /Fosrc\absolute.obj /c src\absolute.cpp /std=c++17 /nologo /ID:\usr\include
          scons
          ./dist/tests
        env:
          FILENAME: tests
          DIRNAME: dist
