name: Test on Windows 2022

on: [push, pull_request]

jobs:
  test:
    name: Test on Windows 2022
    runs-on: windows-2022

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install gtest from source
        run: |
          git clone https://github.com/google/googletest.git -b release-1.12.0
          mkdir googletest/build
          cd googletest/build
          cmake .. -G "MinGW Makefiles" \
          -DCMAKE_C_COMPILER==c:/programdata/chocolatey/bin/gcc.exe \
          -DCMAKE_CXX_COMPILER==c:/programdata/chocolatey/bin/g++.exe
          make

      - name: Build tests
        run: |
          mkdir dist
          c:/programdata/chocolatey/bin/g++.exe $(find src test -name "*.cpp") \
          -std=c++11 -Igoogletest/googletest/include -Lgoogletest/build/lib -lgtest -o dist/test

      - name: Run tests
        run: |
          export FILENAME=$PWD/dist/test
          dist/test.exe
