name: Test on Windows 2022

on: [push, pull_request]

jobs:
  review:
    runs-on: windows-2022
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-windows

      - name: Run tests
        run: |
          export FILEPATH=$PWD/dist/tests
          export DIRPATH=$PWD/dist
          export ABSPATH=$PWD/dist/a/b/c          
          scons
          ./dist/tests
        shell: bash
        env:
          PYTHONUTF8: 1
          CPPPATH: /usr/include
          LIBPATH: /usr/lib
          FILENAME: tests
          DIRNAME: dist