name: Test on Windows 2022

on: [push, pull_request]

jobs:
  review:
    runs-on: windows-2022
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-windows

      - name: Run tests
        run: |
          set FILEPATH=%cd%/dist/tests
          set DIRPATH=%cd%/dist
          set ABSPATH=%cd%/dist/a/b/c
          scons
          ./dist/tests
        env:
          FILENAME: tests
          DIRNAME: dist
          CPPPATH: C:/Program Files (x86)
          LIBPATH: C:/Program Files (x86)